# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './feature-candy-ui/mainwindow.ui'
#
# Created: Mon Sep 21 17:56:33 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 589)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtGui.QGraphicsView(self.centralWidget)
        self.graphicsView.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setResizeAnchor(QtGui.QGraphicsView.AnchorUnderMouse)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 734, 173))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.selectModelButton = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.selectModelButton.setObjectName("selectModelButton")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.selectModelButton)
        self.modelPathLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelPathLabel.sizePolicy().hasHeightForWidth())
        self.modelPathLabel.setSizePolicy(sizePolicy)
        self.modelPathLabel.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.modelPathLabel.setScaledContents(False)
        self.modelPathLabel.setWordWrap(False)
        self.modelPathLabel.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.modelPathLabel.setObjectName("modelPathLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.modelPathLabel)
        self.selectWeightsButton = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.selectWeightsButton.setObjectName("selectWeightsButton")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.selectWeightsButton)
        self.weightsPathLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.weightsPathLabel.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.weightsPathLabel.setObjectName("weightsPathLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.weightsPathLabel)
        self.selectMeanButton = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.selectMeanButton.setObjectName("selectMeanButton")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.selectMeanButton)
        self.meanPathLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.meanPathLabel.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.meanPathLabel.setObjectName("meanPathLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.meanPathLabel)
        self.gridLayout_3.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.loadModelButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.loadModelButton.setStyleSheet("background-color: rgb(255, 64, 64);")
        self.loadModelButton.setObjectName("loadModelButton")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.loadModelButton)
        self.loadInfoLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadInfoLabel.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.loadInfoLabel.setObjectName("loadInfoLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.loadInfoLabel)
        self.gridLayout_3.addLayout(self.formLayout_3, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 165, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.layersComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.layersComboBox.setObjectName("layersComboBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.layersComboBox)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.showNFilters = QtGui.QSpinBox(self.formLayoutWidget)
        self.showNFilters.setObjectName("showNFilters")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.showNFilters)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 6)
        self.gridLayout.setRowStretch(1, 4)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Feature Candy", None, QtGui.QApplication.UnicodeUTF8))
        self.selectModelButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.modelPathLabel.setText(QtGui.QApplication.translate("MainWindow", "Model definition path...", None, QtGui.QApplication.UnicodeUTF8))
        self.selectWeightsButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.weightsPathLabel.setText(QtGui.QApplication.translate("MainWindow", "Weights path...", None, QtGui.QApplication.UnicodeUTF8))
        self.selectMeanButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.meanPathLabel.setText(QtGui.QApplication.translate("MainWindow", "Mean path...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadModelButton.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.loadInfoLabel.setText(QtGui.QApplication.translate("MainWindow", "No model loaded yet", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Choose Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Choose Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "#filters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Explore filters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))

